<?php

/**
 * @file
 * Makes FMath available as plugin for client-side editors integrated via
 * Wysiwyg API.
 */
 
/**
 * Implements hook_wysiwyg_plugin().
 */
function fmath_wysiwyg_wysiwyg_plugin($editor, $version) {

  switch ($editor) {
    case 'ckeditor':

        return array(
          'fmath_formula' => array(
            // A URL to the plugin's homepage.
            'url' => 'http://www.fmath.info',

            // A list of buttons provided by this native plugin. The key has to
            // match the corresponding JavaScript implementation. The value is
            // is displayed on the editor configuration form only.
            'buttons' => array(
              'fmath_formula' => t('FMath'),
            ),
            
            // Boolean whether the editor needs to load this plugin. When TRUE,
            // the editor will automatically load the plugin based on the 'path'
            // variable provided. If FALSE, the plugin either does not need to
            // be loaded or is already loaded by something else on the page.
            // Most plugins should define TRUE here.
            'load' => TRUE,
            // Boolean whether this plugin is a native plugin, i.e. shipped with
            // the editor. Definition must be ommitted for plugins provided by
            // other modules. TRUE means 'path' and 'filename' above are ignored
            // and the plugin is instead loaded from the editor's plugin folder.
            'internal' => TRUE,
          ),
        );

      break;
  }

}
